from typing import Any, ClassVar

__version__: str

class ArconeError(Exception): ...
class ConfigError(ArconeError): ...
class ApiError(ArconeError): ...
class TimeoutError(ArconeError): ...
class ToolError(ArconeError): ...
class StreamingUnsupportedError(ToolError): ...
class SessionError(ArconeError): ...
class DatabaseError(ArconeError): ...
class KnowledgeError(ArconeError): ...
class RetrievalError(ArconeError): ...

def runtime_info() -> str: ...

class InMemorySessionStore:
    def __init__(self) -> None: ...

class PostgresSessionStore:
    @staticmethod
    async def from_env(
        max_pool_size: int = 16,
        connect_timeout_seconds: float = 5.0,
    ) -> "PostgresSessionStore": ...

class PostgresPool:
    @staticmethod
    async def from_env(
        max_pool_size: int = 16,
        connect_timeout_seconds: float = 5.0,
        statement_timeout_seconds: float | None = None,
    ) -> "PostgresPool": ...

class AgentResponse:
    @property
    def content(self) -> str | None: ...
    @property
    def reasoning_content(self) -> str | None: ...
    @property
    def finish_reason(self) -> str: ...
    @property
    def usage(self) -> dict[str, Any] | None: ...
    @property
    def history(self) -> list[dict[str, Any]]: ...

class AgentStream:
    def __aiter__(self) -> "AgentStream": ...
    async def __anext__(self) -> str: ...
    async def finish(self) -> AgentResponse: ...
    def close(self) -> None: ...

class Agent:
    @staticmethod
    def from_env(
        system: str | None = None,
        model: str | None = None,
        thinking: bool | None = None,
        reasoning_effort: str | None = None,
        max_tokens: int | None = None,
        max_tool_rounds: int | None = None,
        session_id: str | None = None,
        session_store: InMemorySessionStore | PostgresSessionStore | None = None,
    ) -> "Agent": ...
    async def ask_text(self, prompt: str) -> str: ...
    async def ask(self, prompt: str) -> AgentResponse: ...
    async def stream(self, prompt: str) -> AgentStream: ...
    def stream_text(self, prompt: str) -> AgentStream: ...
    def clear_history(self) -> None: ...
    async def clear_session(self) -> None: ...
    def add_tool(
        self,
        name: str,
        description: str,
        schema: dict[str, Any],
        handler: Any,
    ) -> None: ...

class Document:
    @staticmethod
    def text(
        id: str,
        content: str,
        title: str | None = None,
        source: str | None = None,
        path: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> "Document": ...
    @property
    def id(self) -> str: ...
    @property
    def content(self) -> str: ...
    @property
    def title(self) -> str | None: ...
    @property
    def source(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def metadata(self) -> dict[str, Any] | None: ...

class KnowledgeChunk:
    @property
    def id(self) -> str: ...
    @property
    def document_id(self) -> str: ...
    @property
    def chunk_index(self) -> int: ...
    @property
    def content(self) -> str: ...
    @property
    def metadata(self) -> dict[str, Any]: ...

class ScoredChunk:
    @property
    def chunk(self) -> KnowledgeChunk: ...
    @property
    def score(self) -> float: ...

class InMemoryKnowledgeBase:
    def __init__(self, max_chars: int = 1200, overlap_chars: int = 120) -> None: ...
    async def add_document(self, document: Document) -> list[KnowledgeChunk]: ...
    async def list_documents(self) -> list[Document]: ...
    async def remove_document(self, document_id: str) -> bool: ...
    async def chunk_document(self, document: Document) -> list[KnowledgeChunk]: ...
    async def chunks_for_document(self, document_id: str) -> list[KnowledgeChunk]: ...
    async def chunks_for_source(self, source: str) -> list[KnowledgeChunk]: ...

class PostgresKnowledgeBase:
    def __init__(
        self,
        pool: PostgresPool,
        max_chars: int = 1200,
        overlap_chars: int = 120,
    ) -> None: ...
    async def migrate(self) -> None: ...
    async def add_document(self, document: Document) -> list[KnowledgeChunk]: ...
    async def list_documents(self) -> list[Document]: ...
    async def remove_document(self, document_id: str) -> bool: ...
    async def chunk_document(self, document: Document) -> list[KnowledgeChunk]: ...
    async def chunks_for_document(self, document_id: str) -> list[KnowledgeChunk]: ...
    async def chunks_for_source(self, source: str) -> list[KnowledgeChunk]: ...

class OpenAiEmbedder:
    @staticmethod
    def from_env(
        model: str | None = None,
        base_url: str | None = None,
        timeout_seconds: float = 60.0,
    ) -> "OpenAiEmbedder": ...

class InMemoryVectorRetriever:
    def __init__(self, embedder: OpenAiEmbedder) -> None: ...
    async def index(self, chunks: list[KnowledgeChunk]) -> None: ...
    async def retrieve(self, query: str, top_k: int) -> list[ScoredChunk]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...

class PgVectorRetriever:
    def __init__(
        self,
        pool: PostgresPool,
        embedder: OpenAiEmbedder,
        embedding_dimension: int = 1536,
        metric: str = "cosine",
        index_mode: str = "auto",
    ) -> None: ...
    async def migrate(self) -> None: ...
    async def index(self, chunks: list[KnowledgeChunk]) -> None: ...
    async def retrieve(self, query: str, top_k: int) -> list[ScoredChunk]: ...

class KnowledgeSource:
    @property
    def index(self) -> int: ...
    @property
    def chunk_id(self) -> str: ...
    @property
    def document_id(self) -> str: ...
    @property
    def title(self) -> str | None: ...
    @property
    def source(self) -> str | None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def score(self) -> float: ...

class KnowledgeAgentResponse:
    @property
    def content(self) -> str: ...
    @property
    def used_fallback(self) -> bool: ...
    @property
    def sources(self) -> list[KnowledgeSource]: ...
    @property
    def retrieved_chunks(self) -> list[ScoredChunk]: ...
    @property
    def agent_response(self) -> AgentResponse | None: ...

class KnowledgeAgent:
    @staticmethod
    def from_env(
        retriever: InMemoryVectorRetriever | PgVectorRetriever,
        system: str | None = None,
        model: str | None = None,
        thinking: bool | None = None,
        reasoning_effort: str | None = None,
        max_tokens: int | None = None,
        max_tool_rounds: int | None = None,
        top_k: int = 4,
        max_context_chars: int = 6000,
        fallback_message: str | None = None,
    ) -> "KnowledgeAgent": ...
    @staticmethod
    def from_agent(
        agent: Agent,
        retriever: InMemoryVectorRetriever | PgVectorRetriever,
        top_k: int = 4,
        max_context_chars: int = 6000,
        fallback_message: str | None = None,
    ) -> "KnowledgeAgent": ...
    async def ask(self, question: str) -> KnowledgeAgentResponse: ...
